###
GET http://localhost:5000/auth/login

###
POST http://localhost:5000/users
Content-Type: application/json

{
	"firstName":"Test",
	"lastName":"1234",
	"email":"test@gmail.com",
	"password":"test1234"
}

###
GET http://localhost:5000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkEiLCJsYXN0TmFtZSI6IjIzIiwiZW1haWwiOiJ0ZXN0MUBnbWFpbC5jb20ifSwiaWF0IjoxNjQwNDE0MTU3LCJleHAiOjE2NDA0MjQ5NTd9.qjyf-u8Iv_ETSnns60GLCPh5U9LhZu92EuaP3erpUeI

###
GET http://localhost:5000/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkEiLCJsYXN0TmFtZSI6IjIzIiwiZW1haWwiOiJ0ZXN0MUBnbWFpbC5jb20ifSwiaWF0IjoxNjQwNDE0MTU3LCJleHAiOjE2NDA0MjQ5NTd9.qjyf-u8Iv_ETSnns60GLCPh5U9LhZu92EuaP3erpUeI

###
PATCH  http://localhost:5000/users/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkEiLCJsYXN0TmFtZSI6IjIzIiwiZW1haWwiOiJ0ZXN0MUBnbWFpbC5jb20ifSwiaWF0IjoxNjQwNDE0MTU3LCJleHAiOjE2NDA0MjQ5NTd9.qjyf-u8Iv_ETSnns60GLCPh5U9LhZu92EuaP3erpUeI

{
	"firstName":"A",
	"lastName":"23",
	"email":"test5@gmail.com",
	"password":"test5"
}

###
DELETE  http://localhost:5000/users/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyZXN1bHQiOnsiaWQiOjEsImZpcnN0TmFtZSI6IkEiLCJsYXN0TmFtZSI6IjIzIiwiZW1haWwiOiJ0ZXN0MUBnbWFpbC5jb20ifSwiaWF0IjoxNjQwNDE0MTU3LCJleHAiOjE2NDA0MjQ5NTd9.qjyf-u8Iv_ETSnns60GLCPh5U9LhZu92EuaP3erpUeI

###
POST  http://localhost:5000/users/login
Content-Type: application/json

{
	"email":"test1@gmail.com",
	"password":"test1"
}



